"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, GitBranch, Menu, X } from "lucide-react";
import { useEffect, useState } from "react";
import { projects, type Project, type ProjectArt } from "@/data/projects";

const navItems = ["About", "Projects", "Skills", "Contact"];
const ExternalArrow = () => <ArrowUpRight aria-hidden="true" size={15} strokeWidth={1.8} />;

function ProjectVisual({ art, title }: { art: ProjectArt; title: string }) {
  if (art === "astro") return <div className="art art-astro" role="img" aria-label={`${title} interface placeholder`}><div className="star-field" /><div className="astro-window"><div className="window-bar"><span /><span /><span /><b>ASTRODESK</b></div><div className="astro-content"><aside><i /><i /><i /><i /></aside><div className="astro-sky"><span className="moon" /><span className="constellation">✦</span><small>Tonight · 21:47</small></div><div className="astro-panel"><b>Clear skies</b><span>14° · Low moon</span><div className="graph" /></div></div></div><p className="art-caption">Desktop workspace / Screenshot placeholder</p></div>;
  if (art === "seven") return <div className="art art-seven" role="img" aria-label={`${title} interface placeholder`}><div className="seven-glow" /><div className="seven-screen"><div className="seven-nav"><b>SEVEN</b><span>Home&nbsp;&nbsp; Movies&nbsp;&nbsp; Series</span></div><div className="seven-title"><small>NOW STREAMING</small><strong>THE<br />GOOD<br />DOCTOR</strong><button>▶ Watch now</button></div><div className="poster-row"><i /><i /><i /><i /></div></div><p className="art-caption">Cinematic web / app preview</p></div>;
  if (art === "kiosk") return <div className="art art-kiosk" role="img" aria-label={`${title} menu interface placeholder`}><div className="kiosk-phone"><div className="phone-top">LE KIOSK <span>☰</span></div><b>Cravings,<br />served fresh.</b><div className="food-shape"><i /><i /><i /></div><div className="kiosk-pills"><span>Waffles</span><span>Drinks</span><span>Ice cream</span></div></div><p className="art-caption">Live restaurant platform / Mobile preview</p></div>;
  if (art === "yalout") return <div className="art art-yalout" role="img" aria-label={`${title} mobile interface placeholder`}><div className="yalout-card"><small>YALLA, WEIN RAYHIN?</small><b>Where should<br />we go tonight?</b><div className="vote-bars"><span /><span /><span /></div><div className="choice"><i>☀</i><span><b>Gemmayzeh</b><small>6 votes · Food & drinks</small></span><em>+</em></div></div><p className="art-caption">Mobile planning app / Screenshot placeholder</p></div>;
  return <div className="art art-shelf" role="img" aria-label={`${title} store interface placeholder`}><div className="shelf-browser"><div className="shelf-header"><b>THE TECH SHELF</b><span>Search&nbsp; Cart (0)</span></div><div className="shelf-main"><div><small>RELIABLE DIGITAL GOODS</small><b>Tools for your<br />digital life.</b><button>Explore store</button></div><div className="product-cube"><i /><i /><i /></div></div></div><p className="art-caption">Storefront / Screenshot placeholder</p></div>;
}

function ProjectSection({ project, index }: { project: Project; index: number }) {
  const reduceMotion = useReducedMotion();
  return <motion.article className={`project ${index % 2 ? "project-reverse" : ""} ${project.featured ? "project-featured" : ""}`} initial={{ opacity: 0, y: reduceMotion ? 0 : 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}>
    <motion.div whileHover={reduceMotion ? undefined : { y: -5 }} transition={{ duration: 0.35 }}><ProjectVisual art={project.art} title={project.title} /></motion.div>
    <div className="project-copy"><p className="eyebrow">{project.eyebrow}</p><h3>{project.title}</h3><p className="project-description">{project.description}</p><ul>{project.features.slice(0, 3).map((feature) => <li key={feature}>{feature}</li>)}</ul><div className="tags">{project.tech.map((tech) => <span key={tech}>{tech}</span>)}</div><div className="project-links">{project.github && <a href={project.github} target="_blank" rel="noreferrer">View GitHub <ExternalArrow /></a>}{project.live && <a href={project.live} target="_blank" rel="noreferrer">View live site <ExternalArrow /></a>}</div></div>
  </motion.article>;
}

function GithubSnapshot() {
  const [repositoryCount, setRepositoryCount] = useState<number | null>(null);
  useEffect(() => { fetch("https://api.github.com/users/joetheproz5").then((response) => response.ok ? response.json() : null).then((profile) => { if (profile?.public_repos) setRepositoryCount(profile.public_repos); }).catch(() => undefined); }, []);
  return <section className="github-band" aria-label="GitHub profile"><p className="eyebrow">On GitHub</p><div><h2>Building in the open.</h2><p>{repositoryCount ? `${repositoryCount}+ public repositories and ongoing work.` : "Browse selected projects and ongoing work."}</p></div><a className="button button-light" href="https://github.com/joetheproz5" target="_blank" rel="noreferrer"><GitBranch size={17} /> Visit GitHub <ExternalArrow /></a></section>;
}

export function Portfolio() {
  const [menuOpen, setMenuOpen] = useState(false);
  const reduceMotion = useReducedMotion();
  return <main>
    <header className="site-header"><a className="wordmark" href="#home" aria-label="Joe Ghaoui home">JG<span>.</span></a><nav className="desktop-nav" aria-label="Main navigation">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`}>{item}</a>)}</nav><a className="github-icon" href="https://github.com/joetheproz5" target="_blank" rel="noreferrer" aria-label="Joe Ghaoui on GitHub"><GitBranch size={19} /></a><button className="menu-trigger" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><AnimatePresence>{menuOpen && <motion.nav className="mobile-nav" initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} aria-label="Mobile navigation">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<a href="https://github.com/joetheproz5" target="_blank" rel="noreferrer">GitHub <ExternalArrow /></a></motion.nav>}</AnimatePresence></header>
    <section id="home" className="hero section"><div className="hero-grid" aria-hidden="true"><i /><i /><i /><i /></div><motion.p className="eyebrow hero-label" initial={{ opacity: 0, y: reduceMotion ? 0 : 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>Software developer · Computer Science student</motion.p><motion.h1 initial={{ opacity: 0, y: reduceMotion ? 0 : 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.18, ease: [0.22, 1, 0.36, 1] }}>Joe<br /><span>Ghaoui</span></motion.h1><motion.div className="hero-bottom" initial={{ opacity: 0, y: reduceMotion ? 0 : 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.32 }}><p>I build useful, polished applications—from desktop software and web platforms to automation tools and client projects.</p><div className="hero-actions"><a className="button button-red" href="#projects">View projects <ArrowDownRight size={17} /></a><a className="button button-line" href="#contact">Contact me <ArrowUpRight size={16} /></a></div></motion.div><motion.div className="signal" animate={reduceMotion ? undefined : { opacity: [0.45, 1, 0.45] }} transition={{ repeat: Infinity, duration: 3.5 }}><span /> Available for work</motion.div></section>
    <section id="about" className="about section"><p className="eyebrow">01 / About</p><div className="about-copy"><h2>I like building software that earns its place in someone’s day.</h2><div><p>I’m a Computer Science student and developer working across desktop apps, websites and experimental tools. I’m drawn to complete products—the kind that solve a real problem, not just a small piece of one.</p><a className="inline-link" href="#projects">Explore my work <ArrowDownRight size={17} /></a></div></div></section>
    <section id="projects" className="projects-section section"><div className="section-intro"><p className="eyebrow">02 / Selected projects</p><h2>Work with range.</h2><p>From a Windows astrophotography workspace to live client systems, these are the products I’ve been shaping.</p></div><div className="projects-list">{projects.map((project, index) => <ProjectSection key={project.title} project={project} index={index} />)}</div></section>
    <section id="skills" className="skills section"><p className="eyebrow">03 / Tools I use</p><div className="skills-layout"><h2>A practical stack<br />for shipping things.</h2><div className="skill-groups"><div><p>Languages</p><span>C# · JavaScript · TypeScript · HTML · CSS</span></div><div><p>Frameworks & platforms</p><span>.NET · WPF · React · Next.js · Tailwind CSS</span></div><div><p>Tools & systems</p><span>Git · GitHub · VS Code · Supabase · ADB · scrcpy · Siril</span></div><div><p>What I do</p><span>Responsive web design · REST APIs · Automation · Desktop development</span></div></div></div></section>
    <section className="practice section"><p className="eyebrow">04 / What I do</p><div className="practice-grid"><article><span>01</span><h3>Web development</h3><p>Responsive websites, interfaces and web applications with a clear focus on the details.</p></article><article><span>02</span><h3>Desktop development</h3><p>Windows applications and tools built with C# and .NET for focused workflows.</p></article><article><span>03</span><h3>Automation & tooling</h3><p>Software that connects devices and external tools to make repeatable work simpler.</p></article><article><span>04</span><h3>Client projects</h3><p>Custom websites and systems for real businesses, from first interface to deployment.</p></article></div></section>
    <GithubSnapshot />
    <section id="contact" className="contact section"><p className="eyebrow">05 / Contact</p><h2>Have something<br />worth building?</h2><p>Get in touch and tell me what you have in mind.</p><a className="contact-github" href="https://github.com/joetheproz5" target="_blank" rel="noreferrer">Find me on GitHub <ExternalArrow /></a></section>
    <footer><a className="wordmark" href="#home">JG<span>.</span></a><p>© {new Date().getFullYear()} Joe Ghaoui</p><a href="#home">Back to top ↑</a></footer>
  </main>;
}
